version: '3.9'

services:

  db-microservice-spring-keycloak:
    image: postgres:16.4-alpine
    container_name: microservice-spring-keycloak-postgres164
    environment:
      - POSTGRES_USER=${DATASOURCE_USER}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${KEYCLOAK_DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - microservice-spring-keycloak-postgres:/var/lib/postgresql/data
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DATASOURCE_USER} -d ${KEYCLOAK_DATABASE_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      # Configure a database vendor
      KC_DB: postgres
      KC_DB_URL_HOST: db-microservice-spring-keycloak
      KC_DB_URL_DATABASE: ${KEYCLOAK_DATABASE_NAME}
#      KC_DB_URL: ${DATASOURCE_URL}${KEYCLOAK_DATABASE_NAME}
      KC_DB_USERNAME: ${DATASOURCE_USER}
      KC_DB_PASSWORD: ${DATASOURCE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
      # Enable health support
      KC_HEALTH_ENABLED: true
      # Enable metrics support
      KC_METRICS_ENABLED: true
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_FRONTEND_URL}
#      KC_HOSTNAME_PATH:
#      KEYCLOAK_BASE_URL:
#      FRONTEND_BASE_URL
      # not documented configuration option
#      KEYCLOAK_SECRET: ?
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      LOG_LEVEL: DEBUG
    ports:
      - "8070:8080"
      - "9000:9000"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 5s
      timeout: 5s
      retries: 30
    depends_on:
      db-microservice-spring-keycloak:
        condition: service_healthy
    command:
      - start-dev
      - "--import-realm"

  service:
    container_name: service
    build:
      context: ../service/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_HOST=${KEYCLOAK_HOST}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT=${KEYCLOAK_CLIENT}
    depends_on:
      keycloak:
        condition: service_healthy

volumes:
  microservice-spring-keycloak-postgres:
