version: '3.9'

services:

  db-microservice-spring-keycloak:
    image: postgres:16.2-alpine
    container_name: microservice-spring-keycloak-postgres162
    environment:
      - POSTGRES_USER=${DATASOURCE_USER}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${KEYCLOAK_DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - microservice-spring-keycloak-postgres:/var/lib/postgresql/data
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DATASOURCE_USER} -d ${KEYCLOAK_DATABASE_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db-microservice-spring-keycloak
      KC_DB_URL_DATABASE: ${KEYCLOAK_DATABASE_NAME}
#      KC_DB_URL: ${DATASOURCE_URL}${KEYCLOAK_DATABASE_NAME}
      KC_DB_USERNAME: ${DATASOURCE_USER}
      KC_DB_PASSWORD: ${DATASOURCE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
      LOG_LEVEL: DEBUG
    ports:
      - "8070:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      db-microservice-spring-keycloak:
        condition: service_healthy
    command:
      - start-dev
      - "--import-realm"

volumes:
  microservice-spring-keycloak-postgres:
